# arr = list(map(int, input().split(' ')))
arr = [0, 1, 2, 1, 1, 2, 1, 1, 0, 0, 1, 1, 2, 0]
zc = arr.count(0)
oc = arr.count(1)
tc = arr.count(2)
ans = []
ans[0:zc] = [0]*zc
ans[zc:oc] = [1]*oc
ans[zc+oc:tc] = [2]*tc
